# Generated by Django 4.2.7 on 2025-07-03 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Training Session', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('epochs', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('batch_size', models.IntegerField(default=32, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('learning_rate', models.FloatField(default=0.001, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1.0)])),
                ('kernel_size', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dropout_rate', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('filters', models.TextField(default='[32, 64, 128]')),
                ('training_accuracy', models.FloatField(blank=True, null=True)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('test_accuracy', models.FloatField(blank=True, null=True)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('test_loss', models.FloatField(blank=True, null=True)),
                ('training_time', models.FloatField(blank=True, null=True)),
                ('model_file', models.CharField(blank=True, max_length=500, null=True)),
                ('history_plot', models.CharField(blank=True, max_length=500, null=True)),
                ('confusion_matrix_plot', models.CharField(blank=True, max_length=500, null=True)),
                ('training_history', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Model Comparison', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comparison_plot', models.CharField(blank=True, max_length=500, null=True)),
                ('comparison_results', models.TextField(blank=True, null=True)),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_model1', to='dashboard.trainingsession')),
                ('model2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_model2', to='dashboard.trainingsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='data_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('n_samples', models.IntegerField(blank=True, null=True)),
                ('n_channels', models.IntegerField(blank=True, null=True)),
                ('sampling_rate', models.IntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoTuningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Auto-Tuning Session', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('search_type', models.CharField(choices=[('grid_search', 'Grid Search'), ('random_search', 'Random Search')], default='random_search', max_length=20)),
                ('max_trials', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('max_time', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)])),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('best_parameters', models.TextField(blank=True, null=True)),
                ('total_trials', models.IntegerField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('results_file', models.CharField(blank=True, max_length=500, null=True)),
                ('optimization_plot', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
